apiVersion: batch/v1
kind: Job
metadata:
  name: noobaa-tests-s3
spec:
  template:
    spec:
      containers:
      - name: noobaa-tests-s3
        image: noobaa-tester:s3-tests
        command: 
            - /bin/bash
            - -c
            - "cd /root/node_modules/noobaa-core/; node ./src/test/system_tests/setup_ceph_s3_config.js; sleep 10; node ./src/test/system_tests/test_ceph_s3.js"
        envFrom:
          - secretRef:
              name: noobaa-admin
      restartPolicy: Never
  completions: 1
  parallelism: 1
  backoffLimit: 0

