name: check-date
on: workflow_dispatch


jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Print
        run: echo ${{ steps.date.outputs.date }}
