name: check-something
run-name: ${{ github.actor }} running test job
on: workflow_dispatch

jobs:
  check-something:
    runs-on: ubuntu-latest
    steps:
    - name: My check
      run: |
       set -x
       export flag=false
       sleep 5 && flag=true &
       my_pid=$!
       echo ${flag}
       wait -n ${my_pid}
       echo ${flag}
