name: check-date
on: workflow_dispatch


jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: date
        run: echo "{name}={$(date +'%Y%m%d')}" >> $GITHUB_OUTPUT
      - name: Prepare
        run: |
          VERSION="${{ steps.date.outputs.date }}"
          echo ${VERSION}
