
name: check var
on: workflow_dispatch

jobs:
  check_var:
    runs-on: ubuntu-latest
    steps:
      - name: Check var
        run: |
         JOB_FAILED=false
         echo "JOB_FAILED is ${JOB_FAILED}"
         if (true)
         then JOB_FAILED=true
         fi
         echo "JOB_FAILED is ${JOB_FAILED}"
         if (JOB_FAILED)
         echo "JOB_FAILED is ${JOB_FAILED}"
         exit 1
         fi
