name: check-docker-sudo
on: 
  workflow_dispatch:

jobs:
  check-docker-sudo:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:

      - name: Check
        run: |
          docker manifest inspect noobaa/noobaa-core:master-20230501 > /dev/null || exit 1
          echo "::found version master-20230501, updating image version"
