name: check-stop
on: [workflow_dispatch, push, pull_request]

jobs:
  check-stop:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
    
    - name: My check
      run: |
       set -x
       counter=0
       echo ${counter}
       sleep 30
       let "counter=counter+1"
       echo ${counter}
       sleep 30
       let "counter=counter+1"
       echo ${counter}
       sleep 30
