
name: check-time-with-schedule
on: 
  schedule:
    - cron: "50 10 * * *"

jobs:
  check-time-with-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
         set -x
         START=$(date)
         echo ${START}
         sleep 5s
         END=$(date)
         echo ${END}
