
name: check-time-with-schedule
on: 
  schedule:
    - cron: "00 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
  workflow_dispatch:

jobs:
  check-time-with-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
         set -x
         START=$(date)
         echo ${START}
         sleep 5s
         END=$(date)
         echo ${END}
