name: check-loop
on: workflow_dispatch

jobs:
  check-loop:
    runs-on: ubuntu-latest
    steps:
    - name: My check
      run: |
       MAX_ITERATIONS=20
       counter=0
       set -x
       while true; do
         let "counter=counter+1"
         if [ "$counter" -ge "$MAX_ITERATIONS" ]; then
          echo "Max iterations reached. Exiting loop."
          break
        fi
        sleep 1
       done
       
