name: nsfs-ceph-s3-tests-check
# on: [push, pull_request, workflow_dispatch]
on: workflow_dispatch

jobs:
  nsfs-ceph-s3-tests:
    runs-on: ubuntu-latest
    # timeout-minutes: 90
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    #   cancel-in-progress: true
    steps:
      # - name: Checkout noobaa-core
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'noobaa/noobaa-core'
      #     path: 'noobaa-core'
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'shirady/noobaa-core'
          ref: nsfs-ceph-tests
          path: 'noobaa-core'
          
      - name: Run NSFS Ceph s3-tests
        run: |
          set -x
          cd ./noobaa-core
          mkdir -p logs/ceph-nsfs-test-logs
          chmod 777 logs/ceph-nsfs-test-logs
          make test-nsfs-cephs3

    # Uncomment this step in case where you want to connect to the VM of this workflow using SSH.
    # Pay attention that this workflow was configured with a timeout, and you might change it for this step.  
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
