# name: check-input2
# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning' 
# #         type: choice
# #         options:
# #          - "1"
# #          - "2"
#         options: ${{ github.ref }}

# jobs:
#   check-input2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print the input branch
#         run: echo  The tags are ${{ github.ref }}
