name: check-stop2
on: workflow_dispatch
concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true


jobs:
  check-stop2:
    runs-on: ubuntu-latest
    steps:
    - name: My check
      run: |
       set -x
       counter=0
       echo ${counter}
       sleep 30
       let "counter=counter+1"
       echo ${counter}
       sleep 30
       let "counter=counter+1"
       echo ${counter}
       sleep 30
