name: check-date
on: workflow_dispatch


jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: date
        run: |
         my_date=$(date +'%Y%m%d')
         echo "{name}={my_date}" >> $GITHUB_OUTPUT
      - name: Prepare
        run: |
          VERSION="${{ steps.date.outputs.date }}"
          echo ${VERSION}
