
name: check-time-with-schedule
on: 
  workflow_dispatch:
  # Run every day at 10:30 and 11:30 UTC
  schedule:
    - cron: "30 10,11 * * *"

jobs:
  check-time-with-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
         set -x
         START=$(date)
         echo ${START}
         sleep 5s
         END=$(date)
         echo ${END}
