
name: check-time
on: workflow_dispatch

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
         set -x
         START=$(date)
         echo ${START}
         sleep 5s
         END=$(date)
         echo ${END}
         echo END ${END} START ${START}
