
name: check var
on: workflow_dispatch

jobs:
  check_var:
    runs-on: ubuntu-latest
    steps:
      - name: Check var
        run: |
         JOB_FAILED=false
         echo ::set-output name=jobstatus::${JOB_FAILED}
         if (true)
         then JOB_FAILED=true
         fi
         echo ::set-output name=jobstatus::${JOB_FAILED}
