name: check-date
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Build From'
        required: true
      tag:
        description: 'Additional tag for the build (such as alpha, beta, etc.) - Optional'
        default: ''

jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Print Date
        run: echo ${{ steps.date.outputs.date }}
      - name: Prepare Suffix
        id: suffix
        if: ${{ github.event.inputs.tag != '' }}
        run: echo suffix="-${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
      - name: Print Suffix
        run: echo ${{ steps.suffix.outputs.suffix }}
