name: Manual noobaa-operator Build and Push Image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to Build From"
        required: true

jobs:
  manual-build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'shirady/noobaa-operator'
          ref: ${{ github.event.inputs.branch }}
          path: 'noobaa-operator'

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Login to Quay Registry
        run: echo ${{ secrets.QUAY_PASS }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Prepare Tags
        id: prep
        run: |
          NOOBAA_TAG=quay.io/${{ secrets.QUAY_USERNAME }}/noobaa-operator:${{ github.event.inputs.branch }}-${{ steps.date.outputs.date }}
          echo "noobaa_tag=${NOOBAA_TAG}" >> $GITHUB_OUTPUT
    
      - name: Build Image
        run: |
          cd noobaa-operator
          make image IMAGE=${{ steps.prep.outputs.noobaa_tag }}
