name: publish-logs3
on: workflow_dispatch

jobs:
  publish-logs3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
       set -x
       mkdir hello
       touch world.txt
       echo hello > hello/world.txt
       ls -l
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: hello
