

name: small-check
on: workflow_dispatch

jobs:
  small-check:
    runs-on: ubuntu-latest
    steps:
    - name: My check
      run: |
       set -x
       counter=0
       echo ${counter}
       ((counter++))
       echo ${counter}
       ((counter++))
       echo ${counter}
